name: fragua_custom_widgets
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.14.0  # Para hacer zoom a las im√°genes
  syncfusion_flutter_pdfviewer: ^26.2.9  # Para visualizar archivos PDF en todos lados
  flutter_pdfview: ^1.2.7 # Para visualizar archivos PDF en Web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: